apps/cart/urls.py
from django.urls import path
from apps.cart.views import CartDetailView, QuantityChangeLogics
from .views import add_to_favorite, remove_from_favorite

urlpatterns = [
    path('cart/', CartDetailView.as_view(), name='cart'),
    path('minus/<int:pk>', QuantityChangeLogics.minus_quantity, name='minus_quantity'),
    path('plus/<int:pk>', QuantityChangeLogics.plus_quantity, name='plus_quantity'),

    path('product/<int:product_id>/add-to-favorite/', add_to_favorite, name='add_to_favorite'),
    path('favorite/<int:favorite_id>/remove/', remove_from_favorite, name='remove_from_favorite'),
]

apps/flours/urls.py
from django.urls import include, path

from apps.flours.views import FlourListView

urlpatterns = [
    path('', FlourListView.as_view(), name='flour_list'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('apps.products.urls')),
    path('', include('apps.cakes.urls')),
    # path('', include('apps.flours.urls')),
    # path('', include('apps.cart.urls.py')),
    # path('login/', LoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cakes/models.py
import os
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from utils.image_path import upload_cakes
from mptt.models import MPTTModel, TreeForeignKey


class Cake(MPTTModel):
    title = models.CharField(
        max_length=50,
        verbose_name="Название",
    )
    description = RichTextField(
        verbose_name="Описание",
    )
    image = models.ImageField(
        upload_to='categories/',
        blank=True,
        null=True,
        verbose_name="Картинка",
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создание",
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name='children',
        null=True,
        blank=True,
        verbose_name="Наследование"
    )
    # slug = models.SlugField(
    #     max_length=100,
    #     unique=True,
    #     blank=True,
    #     null=True,
    # )

    class MPTTMeta:
        order_insertion_by = ['title']

        def get_absolute_url(self):
            return reverse(
                'product_detail',
                kwargs={'slug': self.slug}
            )

    def __str__(self):
        return self.title


class CakeImage(models.Model):
        cake = models.ForeignKey(
            'Cake', on_delete=models.CASCADE,
            related_name='images',
            verbose_name="Торт",
        )
        image = models.ImageField(
            upload_to=upload_cakes,
            verbose_name="Картинка",
        )

        def delete(self, using=None, keep_parents=False):
            os.remove(self.image.path)
            super().delete(using=None, keep_parents=False)

        def __str__(self):
            return f"{self.image.url}"

apps/cart/models.py
from django.db import models

from django.conf import settings


from apps.products.models import Product
from django.contrib.auth import get_user_model

User = get_user_model()


class Cart(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE,
        related_name='cart',
        verbose_name='Пользователь'
    )

    def __str__(self):
        return f"{self.user}"

    def get_total_sum(self):
        return sum(i.get_subtotal_sum() for i in self.items_cart.all())

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'


class Item(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='cart_item',
        verbose_name='Продукт'
    )
    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name='Количество',
    )
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE,
        related_name='items_cart',
        verbose_name='Корзина'
    )

    def get_subtotal_sum(self):
        return int(self.quantity * self.product.price)

    def __str__(self):
        return f"{self.product.title}"

    class Meta:
        verbose_name = 'Элемент корзина'
        verbose_name_plural = 'Элемент корзины'


class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

apps/flours/models.py
from django.db import models
import os
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from utils.image_path import upload_flours
from mptt.models import MPTTModel, TreeForeignKey


class Flour(MPTTModel):
    title = models.CharField(
        max_length=50,
        verbose_name="Название",
    )
    description = RichTextField(
        verbose_name="Описание",
    )
    image = models.ImageField(
        upload_to='categories/',
        blank=True,
        null=True,
        verbose_name="Картинка",
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создание",
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name='children',
        null=True,
        blank=True,
        verbose_name="Наследование"
    )

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return self.title


class FlourImage(models.Model):
        flour = models.ForeignKey(
            'Flour', on_delete=models.CASCADE,
            related_name='images',
            verbose_name="Торт",
        )
        image = models.ImageField(
            upload_to=upload_flours,
            verbose_name="Картинка",
        )

        def delete(self, using=None, keep_parents=False):
            os.remove(self.image.path)
            super().delete(using=None, keep_parents=False)

        def __str__(self):
            return f"{self.image.url}"

apps/cart/forms.py
from django import forms
from apps.cart.models import Favorite


class AddToFavoriteForm(forms.ModelForm):
    class Meta:
        model = Favorite
        fields = []

apps/cart/views.py
from django.views import generic
from django.shortcuts import render, redirect

from apps.cart.models import Cart, Item

from apps.cart.models import Favorite
from apps.cart.forms import AddToFavoriteForm


class CartDetailView(generic.ListView):
    template_name = 'cart-detail.html'
    context_object_name = 'cart'

    def get_queryset(self):
        return Cart.objects.get(user=self.request.user)


class QuantityChangeLogics:

    @staticmethod
    def minus_quantity(request, pk):
        item = Item.objects.get(id=pk)
        if item.quantity -1 == 0:
            item.delete()
            return redirect('cart')
        item.quantity -= 1
        item.save()
        return redirect('cart')

    def plus_quantity(request, pk):
        item = Item.objects.get(id=pk)
        item.quantity += 1
        item.save()
        return redirect('cart')





def add_to_favorite(request, product_id):
    if request.method == 'POST':
        form = AddToFavoriteForm(request.POST)
        if form.is_valid():
            favorite = form.save(commit=False)
            favorite.user = request.user
            favorite.product_id = product_id
            favorite.save()
            return redirect('product_detail', product_id=product_id)
    else:
        form = AddToFavoriteForm()
    return render(request, 'add_to_favorite.html', {'form': form})


def remove_from_favorite(request, favorite_id):
    favorite = Favorite.objects.get(id=favorite_id)
    favorite.delete()
    return redirect('favorites_list')

apps/flours/views.py
from django.shortcuts import render
from django.views import generic
from apps.flours.models import Flour


class FlourListView(generic.ListView):
    model = Flour
    template_name = 'index.html'


def about(request):
    return render(request, 'about.html')

templates/about.html
    <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Barbol - Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="../static/assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="../static/css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">
                    <img src="../static/images/logo.png" alt="" class="navbar-brand-logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="index.html">Главная</a></li>
                        <li class="nav-item"><a class="nav-link active" href="#!">О Нас</a></li>
                        <li class="nav-item"><a class="nav-link" href="torts.html">Торты</a></li>
                        <li class="nav-item"><a class="nav-link" href="flour.html">Мучное</a></li>

                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li> -->
                    </ul>
                    
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Корзина
                            <span class="badge bg-dark text-white ms-1 rounded-pill" style="background-color: green;">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5" style="background-image: url(./../images/header.jpg); background-repeat: no-repeat; background-size: 100%;">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">О нас</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Мы компания которая делает с душой</p>
                </div>
            </div>
        </header>

        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="../static/images/barbolabout.jpg" alt="..."></div>
                    <div class="col-md-6">
                        <h1 class="display-5 fw-bolder">Барбол это то что вы искали</h1>
                        <br>
                        <br>
                        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium at dolorem quidem modi. Nam sequi consequatur obcaecati excepturi alias magni, accusamus eius blanditiis delectus ipsam minima ea iste laborum vero?</p>
                        <br>
                        <br>
                        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium at dolorem quidem modi. Nam sequi consequatur obcaecati excepturi alias magni, accusamus eius blanditiis delectus ipsam minima ea iste laborum vero?</p>

                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Barbol Market 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="../static/js/scripts.js"></script>
    </body>
</html>

templates/cart.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Barbol - Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="../static/assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="../static/css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">
                    <img src="../static/images/logo.png" alt="" class="navbar-brand-logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="index.html">Главная</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">О Нас</a></li>
                        <li class="nav-item"><a class="nav-link" href="torts.html">Торты</a></li>
                        <li class="nav-item"><a class="nav-link" href="flour.html">Мучное</a></li>

                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li> -->
                    </ul>
                    
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Корзина
                            <span class="badge bg-dark text-white ms-1 rounded-pill" style="background-color: green;">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5" style="background-image: url(./../images/header.jpg); background-repeat: no-repeat; background-size: 100%;">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Корзина</h1>
                </div>
            </div>
        </header>
        <!-- Section First-->

        <section class="h-100 h-custom" style="background-color: #d2c9ff;">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12">
                  <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                    <div class="card-body p-0">
                      <div class="row g-0">
                        <div class="col-lg-8" style="width: 100%;">
                          <div class="p-5">
                            <div class="d-flex justify-content-between align-items-center mb-5">
                              <h1 class="fw-bold mb-0 text-black">Shopping Cart</h1>
                              <h6 class="mb-0 text-muted">3 items</h6>
                            </div>
                            <hr class="my-4">
          
                            <div class="row mb-4 d-flex justify-content-between align-items-center">
                              <div class="col-md-2 col-lg-2 col-xl-2">
                                <img
                                  src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img7.webp"
                                  class="img-fluid rounded-3" alt="Cotton T-shirt">
                              </div>
                              <div class="col-md-3 col-lg-3 col-xl-3">
                                <h6 class="text-muted">Shirt</h6>
                                <h6 class="text-black mb-0">Cotton T-shirt</h6>
                              </div>
                              <div class="col-md-3 col-lg-3 col-xl-2 d-flex" style="padding-left: 60px;">
                                <a href="" style="color: black; text-decoration: none; margin-right: 20px;">
                                    <h4>-</h4>
                                </a>
          
                                <p>
                                    <h3>2</h3>
                                </p>
          
                                
                                <a href="" style="color: black; text-decoration: none; margin-left: 20px;">
                                    <h4>+</h4>
                                </a>
                              </div>
                              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                <h6 class="mb-0">€ 44.00</h6>
                              </div>
                              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                <a href="#!" class="text-muted"><i class="fas fa-times"></i></a>
                              </div>
                            </div>
          
                            <hr class="my-4">

                            <div class="row mb-4 d-flex justify-content-between align-items-center">
                                <div class="col-md-2 col-lg-2 col-xl-2">
                                  <img
                                    src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img7.webp"
                                    class="img-fluid rounded-3" alt="Cotton T-shirt">
                                </div>
                                <div class="col-md-3 col-lg-3 col-xl-3">
                                  <h6 class="text-muted">Shirt</h6>
                                  <h6 class="text-black mb-0">Cotton T-shirt</h6>
                                </div>
                                <div class="col-md-3 col-lg-3 col-xl-2 d-flex" style="padding-left: 60px;">
                                  <a href="" style="color: black; text-decoration: none; margin-right: 20px;">
                                      <h4>-</h4>
                                  </a>
            
                                  <p>
                                      <h3>2</h3>
                                  </p>
            
                                  
                                  <a href="" style="color: black; text-decoration: none; margin-left: 20px;">
                                      <h4>+</h4>
                                  </a>
                                </div>
                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                  <h6 class="mb-0">€ 44.00</h6>
                                </div>
                                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                  <a href="#!" class="text-muted"><i class="fas fa-times"></i></a>
                                </div>
                              </div>
            
                              <hr class="my-4">
          
                            <div class="pt-5" style="display: flex; align-items: center; justify-content: space-around;">
                              <h6 class="mb-0"><a href="index.html" class="text-body"><i
                                    class="fas fa-long-arrow-alt-left me-2"></i>Back to shop</a></h6>
                                <a href="#!" style="text-decoration: none; background-color: green; color: white; padding: 10px; border-radius: 15px;"><h4>Оформить заказ</h4></a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Barbol Market 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="../static/js/scripts.js"></script>
    </body>
</html>

templates/index.html
    {% block title %}
{% endblock %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Barbol - Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="../static/assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">
                    <img src="../static/images/logo.png" alt="" class="navbar-brand-logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'cake_list' %}">Главная</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'cake_list' %}">О Нас</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'cake_list' %}">Торты</a></li>
                        <li class="nav-item"><a class="nav-link" href="f{% url 'cake_list' %}">Мучное</a></li>

                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li> -->
                    </ul>
                    
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Корзина
                            <span class="badge bg-dark text-white ms-1 rounded-pill" style="background-color: green;">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
            {% include 'base/header.html' %}

        <!-- Section First-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <h1 class="title-container">Торты на ваш вкус</h1>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for cake in cake_list %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <a>
                                <img src="{{ cake.images.first.image.url }}" alt="..." />
                            </a>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <a href="#" style="text-decoration: none; color: black;"><h5 class="fw-bolder">{{ cake.title }}</h5></a>
                                    <!-- Product price-->
                                    ${{ cake.price }}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <h1 class="title-container">Мучные изделия</h1>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for cake in cake_list %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img src="{{ cake.images.first.image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ cake.title }}</h5>
                                    <!-- Product price-->
                                    ${{ cake.price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto" href="#"><span id="product-add-cart">Добавить в корзину</span><span id="product-add">В корзину</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

        <!-- Footer-->
{% include 'base/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

{% endblock %}